package org.usf.inspect.jdbc;

import static org.usf.inspect.core.DatabaseAction.COMMIT;
import static org.usf.inspect.core.DatabaseAction.METADATA;
import static org.usf.inspect.core.DatabaseAction.ROLLBACK;
import static org.usf.inspect.core.DatabaseAction.SAVEPOINT;
import static org.usf.inspect.core.DatabaseCommand.SET;
import static org.usf.inspect.core.InspectExecutor.call;
import static org.usf.inspect.core.InspectExecutor.exec;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

/**
 * 
 * @author u$f
 *
 */
@RequiredArgsConstructor
public final class ConnectionWrapper implements Connection {
	
	@Delegate
	private final Connection cn;
	private final DatabaseConnectionLifecycleTracer tracer;
	@Getter
	private ConnectionMetadataCache cache;

	@Override
	public Statement createStatement() throws SQLException {
		return new StatementWrapper(call(cn::createStatement, tracer.statementStageListener(null)), tracer);
	}
	
	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return new StatementWrapper(call(()-> cn.createStatement(resultSetType, resultSetConcurrency), tracer.statementStageListener(null)), tracer);
	}
	
	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new StatementWrapper(call(()-> cn.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), tracer.statementStageListener(null)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, resultSetType, resultSetConcurrency), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, autoGeneratedKeys), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, columnIndexes), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, columnNames), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql, resultSetType, resultSetConcurrency), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), tracer.statementStageListener(sql)), tracer);
	}
	
	@Override
	public Savepoint setSavepoint() throws SQLException {
		return call(cn::setSavepoint, tracer.stageListener(SAVEPOINT));
	}
	
	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		return call(()-> cn.setSavepoint(name), tracer.stageListener(SAVEPOINT));
	}
	
	@Override
	public void commit() throws SQLException {
		exec(cn::commit, tracer.stageListener(COMMIT));
	}
	
	@Override
	public void rollback() throws SQLException {
		exec(cn::rollback, tracer.stageListener(ROLLBACK));
	}
	
	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		exec(()-> cn.rollback(savepoint), tracer.stageListener(ROLLBACK));
	}
	
	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return new DatabaseMetaDataWrapper(call(cn::getMetaData, tracer.stageListener(METADATA)), tracer);
	}
	
	@Override
	public void setCatalog(String catalog) throws SQLException {
		 exec(()-> cn.setCatalog(catalog), tracer.executeStageListener(SET, "catalog="+catalog));
	}
	
	@Override
	public void setSchema(String schema) throws SQLException {
		 exec(()-> cn.setSchema(schema), tracer.executeStageListener(SET, "schema="+schema));
	}
	
	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		 exec(()-> cn.setAutoCommit(autoCommit), tracer.executeStageListener(SET, "autoCommit="+autoCommit));
	}
	
	@Override
	public void close() throws SQLException {
		exec(cn::close, tracer.disconnectionListener());
	}
}
