package org.usf.inspect.jdbc;

import static org.usf.inspect.core.DatabaseAction.COMMIT;
import static org.usf.inspect.core.DatabaseAction.EXECUTE;
import static org.usf.inspect.core.DatabaseAction.METADATA;
import static org.usf.inspect.core.DatabaseAction.ROLLBACK;
import static org.usf.inspect.core.DatabaseAction.SAVEPOINT;
import static org.usf.inspect.core.DatabaseCommand.SET;
import static org.usf.inspect.core.InspectExecutor.call;
import static org.usf.inspect.core.InspectExecutor.exec;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

/**
 * Wraps a {@link Connection} to trace JDBC connection operations.
 *
 * @author u$f
 */
@RequiredArgsConstructor
public final class ConnectionWrapper implements Connection {
	
	@Delegate
	private final Connection cn;
	private final DatabaseRequestMonitor monitor;
	@Getter
	private ConnectionMetadataCache cache;

	/**
	 * Creates a statement for sending SQL statements to the database.
	 *
	 * @return the wrapped statement
	 * @throws SQLException if the statement cannot be created
	 */
	@Override
	public Statement createStatement() throws SQLException {
		return new StatementWrapper(call(cn::createStatement, monitor.statementStageHandler(null)), monitor);
	}
	
	/**
	 * Creates a statement with the given result set type and concurrency.
	 *
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @return the wrapped statement
	 * @throws SQLException if the statement cannot be created
	 */
	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return new StatementWrapper(call(()-> cn.createStatement(resultSetType, resultSetConcurrency), monitor.statementStageHandler(null)), monitor);
	}
	
	/**
	 * Creates a statement with the given result set characteristics.
	 *
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @param resultSetHoldability the result set holdability
	 * @return the wrapped statement
	 * @throws SQLException if the statement cannot be created
	 */
	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new StatementWrapper(call(()-> cn.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), monitor.statementStageHandler(null)), monitor);
	}
	
	/**
	 * Creates a prepared statement for the given SQL.
	 *
	 * @param sql the SQL statement to prepare
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a prepared statement with the given SQL and result set characteristics.
	 *
	 * @param sql the SQL statement to prepare
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, resultSetType, resultSetConcurrency), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a prepared statement with the given SQL and result set characteristics.
	 *
	 * @param sql the SQL statement to prepare
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @param resultSetHoldability the result set holdability
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a prepared statement with the given SQL and generated key mode.
	 *
	 * @param sql the SQL statement to prepare
	 * @param autoGeneratedKeys a flag indicating whether auto-generated keys should be returned
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, autoGeneratedKeys), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a prepared statement with the given SQL and generated key column indexes.
	 *
	 * @param sql the SQL statement to prepare
	 * @param columnIndexes the column indexes to make available for generated keys
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, columnIndexes), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a prepared statement with the given SQL and generated key column names.
	 *
	 * @param sql the SQL statement to prepare
	 * @param columnNames the column names to make available for generated keys
	 * @return the wrapped prepared statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return new PreparedStatementWrapper(call(()-> cn.prepareStatement(sql, columnNames), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a callable statement for the given SQL.
	 *
	 * @param sql the SQL statement to prepare
	 * @return the wrapped callable statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a callable statement with the given SQL and result set characteristics.
	 *
	 * @param sql the SQL statement to prepare
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @return the wrapped callable statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql, resultSetType, resultSetConcurrency), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates a callable statement with the given SQL and result set characteristics.
	 *
	 * @param sql the SQL statement to prepare
	 * @param resultSetType the result set type
	 * @param resultSetConcurrency the result set concurrency
	 * @param resultSetHoldability the result set holdability
	 * @return the wrapped callable statement
	 * @throws SQLException if the statement cannot be prepared
	 */
	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new CallableStatementWrapper(call(()-> cn.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), monitor.statementStageHandler(sql)), monitor);
	}
	
	/**
	 * Creates an unnamed savepoint.
	 *
	 * @return the created savepoint
	 * @throws SQLException if the savepoint cannot be created
	 */
	@Override
	public Savepoint setSavepoint() throws SQLException {
		return call(cn::setSavepoint, monitor.stageHandler(SAVEPOINT));
	}
	
	/**
	 * Creates a named savepoint.
	 *
	 * @param name the savepoint name
	 * @return the created savepoint
	 * @throws SQLException if the savepoint cannot be created
	 */
	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		return call(()-> cn.setSavepoint(name), monitor.stageHandler(SAVEPOINT));
	}
	
	/**
	 * Commits the current transaction.
	 *
	 * @throws SQLException if the transaction cannot be committed
	 */
	@Override
	public void commit() throws SQLException {
		exec(cn::commit, monitor.stageHandler(COMMIT));
	}
	
	/**
	 * Rolls back the current transaction.
	 *
	 * @throws SQLException if the transaction cannot be rolled back
	 */
	@Override
	public void rollback() throws SQLException {
		exec(cn::rollback, monitor.stageHandler(ROLLBACK));
	}
	
	/**
	 * Rolls back the current transaction to the given savepoint.
	 *
	 * @param savepoint the savepoint to roll back to
	 * @throws SQLException if the transaction cannot be rolled back
	 */
	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		exec(()-> cn.rollback(savepoint), monitor.stageHandler(ROLLBACK));
	}
	
	/**
	 * Returns the wrapped database metadata.
	 *
	 * @return the wrapped database metadata
	 * @throws SQLException if the metadata cannot be obtained
	 */
	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return new DatabaseMetaDataWrapper(call(cn::getMetaData, monitor.stageHandler(METADATA)), monitor);
	}
	
	/**
	 * Sets the current catalog.
	 *
	 * @param catalog the catalog name to set
	 * @throws SQLException if the catalog cannot be set
	 */
	@Override
	public void setCatalog(String catalog) throws SQLException {
		 exec(()-> cn.setCatalog(catalog), monitor.stageHandler(EXECUTE, SET, "catalog="+catalog));
	}
	
	/**
	 * Sets the current schema.
	 *
	 * @param schema the schema name to set
	 * @throws SQLException if the schema cannot be set
	 */
	@Override
	public void setSchema(String schema) throws SQLException {
		 exec(()-> cn.setSchema(schema), monitor.stageHandler(EXECUTE, SET, "schema="+schema));
	}
	
	/**
	 * Sets the auto-commit mode for this connection.
	 *
	 * @param autoCommit {@code true} to enable auto-commit
	 * @throws SQLException if the auto-commit mode cannot be changed
	 */
	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		 exec(()-> cn.setAutoCommit(autoCommit), monitor.stageHandler(EXECUTE, SET, "autoCommit="+autoCommit));
	}
	
	/**
	 * Closes the wrapped connection.
	 *
	 * @throws SQLException if the connection cannot be closed
	 */
	@Override
	public void close() throws SQLException {
		exec(cn::close, monitor.disconnectionHandler());
	}
}
