package org.usf.inspect.jdbc;

import static org.usf.inspect.core.DatabaseAction.METADATA;
import static org.usf.inspect.core.InspectExecutor.call;
import static org.usf.inspect.core.InspectExecutor.exec;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

import lombok.experimental.Delegate;

/**
 * Wraps a {@link PreparedStatement} to trace prepared statement execution.
 *
 * @author u$f
 */
public class PreparedStatementWrapper extends StatementWrapper implements PreparedStatement {

	@Delegate(excludes = Statement.class)
	private final PreparedStatement ps;

	/**
	 * Creates a wrapper around the given prepared statement.
	 *
	 * @param ps the prepared statement to wrap
	 * @param tracer the monitor used to trace statement activity
	 */
	public PreparedStatementWrapper(PreparedStatement ps, DatabaseRequestMonitor tracer) {
		super(ps, tracer);
		this.ps = ps;
	}

	/**
	 * Adds the current parameter set to the batch.
	 *
	 * @throws SQLException if the batch cannot be updated
	 */
	@Override
	public void addBatch() throws SQLException {
		exec(ps::addBatch, monitor.addBatchStageHandler(null));
	}
	
	/**
	 * Executes the prepared statement.
	 *
	 * @return {@code true} if the statement returns a result set
	 * @throws SQLException if the statement execution fails
	 */
	@Override
	public boolean execute() throws SQLException {
		return call(ps::execute, monitor.executeStageHandler(null));
	}
	
	/**
	 * Executes the prepared query.
	 *
	 * @return the wrapped result set produced by the query
	 * @throws SQLException if the query execution fails
	 */
	@Override
	public ResultSet executeQuery() throws SQLException {
		return new ResultSetWrapper(call(ps::executeQuery, monitor.executeQueryStageHandler(null)), monitor);
	}
	
	/**
	 * Executes the prepared update statement.
	 *
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public int executeUpdate() throws SQLException {
		return call(ps::executeUpdate, monitor.executeUpdateStageHandler(null));
	}
	
	/**
	 * Executes the prepared statement as a large update.
	 *
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public long executeLargeUpdate() throws SQLException {
		return call(ps::executeLargeUpdate, monitor.executeLargeUpdateStageHandler(null));
	}
	
	/**
	 * Returns the metadata for the result set generated by this prepared statement.
	 *
	 * @return the result set metadata
	 * @throws SQLException if the metadata cannot be obtained
	 */
	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		return call(ps::getMetaData, monitor.stageHandler(METADATA));
	}
}
