package org.usf.inspect.jdbc;

import static org.usf.inspect.core.InspectExecutor.call;
import static org.usf.inspect.core.InspectExecutor.exec;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

/**
 * Wraps a {@link Statement} to trace JDBC statement execution.
 *
 * @author u$f
 */
@RequiredArgsConstructor
public class StatementWrapper implements Statement {

	@Delegate
	protected final Statement st;
	protected final DatabaseRequestMonitor monitor;
	
	/**
	 * Adds the specified SQL statement to the current batch.
	 *
	 * @param sql the SQL statement to add
	 * @throws SQLException if the batch cannot be updated
	 */
	@Override
	public void addBatch(String sql) throws SQLException {
		exec(()-> st.addBatch(sql), monitor.addBatchStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement.
	 *
	 * @param sql the SQL statement to execute
	 * @return {@code true} if the statement returns a result set
	 * @throws SQLException if the statement execution fails
	 */
	@Override
	public boolean execute(String sql) throws SQLException {
		return call(()-> st.execute(sql), monitor.executeStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement and signals whether auto-generated keys should be returned.
	 *
	 * @param sql the SQL statement to execute
	 * @param autoGeneratedKeys a flag indicating whether auto-generated keys should be returned
	 * @return {@code true} if the statement returns a result set
	 * @throws SQLException if the statement execution fails
	 */
	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.execute(sql, autoGeneratedKeys), monitor.executeStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL statement to execute
	 * @param columnIndexes the column indexes to make available for generated keys
	 * @return {@code true} if the statement returns a result set
	 * @throws SQLException if the statement execution fails
	 */
	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.execute(sql, columnIndexes), monitor.executeStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL statement to execute
	 * @param columnNames the column names to make available for generated keys
	 * @return {@code true} if the statement returns a result set
	 * @throws SQLException if the statement execution fails
	 */
	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.execute(sql, columnNames), monitor.executeStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL query.
	 *
	 * @param sql the SQL query to execute
	 * @return the wrapped result set produced by the query
	 * @throws SQLException if the query execution fails
	 */
	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return new ResultSetWrapper(call(()-> st.executeQuery(sql), monitor.executeQueryStageHandler(sql)), monitor);
	}
	
	/**
	 * Executes the specified SQL update statement.
	 *
	 * @param sql the SQL update statement to execute
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public int executeUpdate(String sql) throws SQLException {
		return call(()-> st.executeUpdate(sql), monitor.executeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL update statement and signals whether auto-generated keys should be returned.
	 *
	 * @param sql the SQL update statement to execute
	 * @param autoGeneratedKeys a flag indicating whether auto-generated keys should be returned
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.executeUpdate(sql, autoGeneratedKeys), monitor.executeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL update statement and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL update statement to execute
	 * @param columnIndexes the column indexes to make available for generated keys
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.executeUpdate(sql, columnIndexes), monitor.executeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL update statement and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL update statement to execute
	 * @param columnNames the column names to make available for generated keys
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.executeUpdate(sql, columnNames), monitor.executeUpdateStageHandler(sql));
	}

	/**
	 * Executes all statements currently in the batch.
	 *
	 * @return the update counts for each executed statement
	 * @throws SQLException if the batch execution fails
	 */
	@Override
	public int[] executeBatch() throws SQLException {
		return call(st::executeBatch, monitor.executeBatchStageHandler());
	}
	
	/**
	 * Executes the specified SQL statement as a large update.
	 *
	 * @param sql the SQL statement to execute
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public long executeLargeUpdate(String sql) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql), monitor.executeLargeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement as a large update and signals whether auto-generated keys should be returned.
	 *
	 * @param sql the SQL statement to execute
	 * @param autoGeneratedKeys a flag indicating whether auto-generated keys should be returned
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, autoGeneratedKeys), monitor.executeLargeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement as a large update and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL statement to execute
	 * @param columnIndexes the column indexes to make available for generated keys
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, columnIndexes), monitor.executeLargeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes the specified SQL statement as a large update and makes the indicated columns available for generated keys.
	 *
	 * @param sql the SQL statement to execute
	 * @param columnNames the column names to make available for generated keys
	 * @return the number of affected rows
	 * @throws SQLException if the update execution fails
	 */
	@Override
	public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, columnNames), monitor.executeLargeUpdateStageHandler(sql));
	}
	
	/**
	 * Executes all statements currently in the batch as large updates.
	 *
	 * @return the update counts for each executed statement
	 * @throws SQLException if the batch execution fails
	 */
	@Override
	public long[] executeLargeBatch() throws SQLException {
		return call(st::executeLargeBatch, monitor.executeLargeBatchStageHandler());
	}
	
	/**
	 * Returns the current result set produced by the statement.
	 *
	 * @return the wrapped current result set
	 * @throws SQLException if the result set cannot be obtained
	 */
	@Override
	public ResultSet getResultSet() throws SQLException {
		return new ResultSetWrapper(st.getResultSet(), monitor);
	}
	
	/**
	 * Returns the current update count and reports it to the monitor.
	 *
	 * @return the current update count
	 * @throws SQLException if the update count cannot be obtained
	 */
	@Override
	public int getUpdateCount() throws SQLException {
		var n = st.getUpdateCount();
		monitor.updateStageRowsCount(n);
		return n;
	}
	
	/**
	 * Returns the current large update count and reports it to the monitor.
	 *
	 * @return the current large update count
	 * @throws SQLException if the update count cannot be obtained
	 */
	@Override
	public long getLargeUpdateCount() throws SQLException {
		var n = st.getLargeUpdateCount();
		monitor.updateStageRowsCount(n);
		return n;
	}
}
