package org.usf.inspect.jdbc;

import static org.usf.inspect.core.InspectExecutor.call;
import static org.usf.inspect.core.InspectExecutor.exec;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

/**
 * 
 * @author u$f
 *
 */
@RequiredArgsConstructor
public class StatementWrapper implements Statement {

	@Delegate
	protected final Statement st;
	protected final DatabaseConnectionLifecycleTracer tracer;
	
	@Override
	public void addBatch(String sql) throws SQLException {
		exec(()-> st.addBatch(sql), tracer.addBatchStageListener(sql));
	}
	
	@Override
	public boolean execute(String sql) throws SQLException {
		return call(()-> st.execute(sql), tracer.executeStageListener(sql));
	}
	
	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.execute(sql, autoGeneratedKeys), tracer.executeStageListener(sql));
	}
	
	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.execute(sql, columnIndexes), tracer.executeStageListener(sql));
	}
	
	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.execute(sql, columnNames), tracer.executeStageListener(sql));
	}
	
	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return new ResultSetWrapper(call(()-> st.executeQuery(sql), tracer.executeQueryStageListener(sql)), tracer);
	}
	
	@Override
	public int executeUpdate(String sql) throws SQLException {
		return call(()-> st.executeUpdate(sql), tracer.executeUpdateStageListener(sql));
	}
	
	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.executeUpdate(sql, autoGeneratedKeys), tracer.executeUpdateStageListener(sql));
	}
	
	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.executeUpdate(sql, columnIndexes), tracer.executeUpdateStageListener(sql));
	}
	
	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.executeUpdate(sql, columnNames), tracer.executeUpdateStageListener(sql));
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return call(st::executeBatch, tracer.executeBatchStageListener());
	}
	
	@Override
	public long executeLargeUpdate(String sql) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql), tracer.executeLargeUpdateStageListener(sql));
	}
	
	@Override
	public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, autoGeneratedKeys), tracer.executeLargeUpdateStageListener(sql));
	}
	
	@Override
	public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, columnIndexes), tracer.executeLargeUpdateStageListener(sql));
	}
	
	@Override
	public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
		return call(()-> st.executeLargeUpdate(sql, columnNames), tracer.executeLargeUpdateStageListener(sql));
	}
	
	@Override
	public long[] executeLargeBatch() throws SQLException {
		return call(st::executeLargeBatch, tracer.executeLargeBatchStageListener());
	}
	
	@Override
	public ResultSet getResultSet() throws SQLException {
		return new ResultSetWrapper(st.getResultSet(), tracer);
	}
	
	@Override
	public int getUpdateCount() throws SQLException {
		var n = st.getUpdateCount();
		tracer.updateStageRowsCount(n);
		return n;
	}
	
	@Override
	public long getLargeUpdateCount() throws SQLException {
		var n = st.getLargeUpdateCount();
		tracer.updateStageRowsCount(n);
		return n;
	}
}
