changelog:
  repository: oneteme/inspect-core
  categories:
    - title: 🌟 New Features
      labels:
        - enhancement
    - title: 🐛 Bugs Fixes
      labels:
        - bug
    - title: 📜 Documentation 
      labels:
        - documentation
