package org.usf.traceapi.core;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

/**
 * 
 * @author u$f
 *
 */
@RequiredArgsConstructor
public class StatementWrapper implements Statement {

	@Delegate
	protected final Statement st;
	protected final DatabaseActionTracer tracer;
	
	@Override
	public boolean execute(String sql) throws SQLException {
		return tracer.sql(()-> st.execute(sql));
	}
	
	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return tracer.sql(()-> st.execute(sql, autoGeneratedKeys));
	}
	
	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return tracer.sql(()-> st.execute(sql, columnIndexes));
	}
	
	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return tracer.sql(()-> st.execute(sql, columnNames));
	}
	
	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return tracer.select(()-> st.executeQuery(sql));
	}
	
	@Override
	public int executeUpdate(String sql) throws SQLException {
		return tracer.update(()-> st.executeUpdate(sql));
	}
	
	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return tracer.update(()-> st.executeUpdate(sql, autoGeneratedKeys));
	}
	
	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return tracer.update(()-> st.executeUpdate(sql, columnIndexes));
	}
	
	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return tracer.update(()-> st.executeUpdate(sql, columnNames));
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return tracer.batch(st::executeBatch);
	}
	
	@Override
	public long executeLargeUpdate(String sql) throws SQLException {
		return tracer.update(()-> st.executeLargeUpdate(sql));
	}
	
	@Override
	public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return tracer.update(()-> st.executeLargeUpdate(sql, autoGeneratedKeys));
	}
	
	@Override
	public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return tracer.update(()-> st.executeLargeUpdate(sql, columnIndexes));
	}
	
	@Override
	public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
		return tracer.update(()-> st.executeLargeUpdate(sql, columnNames));
	}
	
	@Override
	public long[] executeLargeBatch() throws SQLException {
		return tracer.batch(st::executeLargeBatch);
	}
}
